# Generated by Django 5.1 on 2024-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='url'),
        ),
    ]
