# Generated by Django 5.1 on 2024-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='is_version_active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=50),
        ),
    ]
