# Generated by Django 5.1 on 2024-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_is_version_active_version_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(max_length=50, verbose_name='Номер версии'),
        ),
    ]
