# Generated by Django 5.1 on 2024-09-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_version_product_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Продукт'),
        ),
    ]
