# Generated by Django 4.2 on 2024-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price', 'created_at', 'updated_at', 'category'], 'permissions': [('can_delete_product', 'Могу отменять публикацию продукта'), ('can_edit_product', 'Могу менять описание продукта'), ('can_edit_category', 'Могу менять категорию продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
